"""empty message

Revision ID: 18377b443743
Revises: 59e43d70120b
Create Date: 2023-01-14 16:07:45.312676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18377b443743'
down_revision = '59e43d70120b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('created_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('created_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
